name: CI - Testes Unitários JS

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  testes:
    name: Executar Testes Unitários
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Instalar dependências
        run: npm install
      
      - name: Dar permissão de execução para o Jest
        run: chmod +x ./node_modules/.bin/jest
      
      - name: Rodar Testes Jest
        run: npm test